services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "8080:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq:/data

  log-worker:
    container_name: log-worker
    image: log-worker
    build:
      context: .
      dockerfile: log-worker/Dockerfile
    volumes:
      - ${LOGS_FOLDER}:/log-folder:rw
    depends_on:
      - seq

volumes:
  seq: